import pandas as pd

# Load the analysis file and the metadata file
analysis_file = "05_self_targeting_analysis.tsv"
metadata_file = "04_updated_with_gc_metadata.tsv"

analysis_data = pd.read_csv(analysis_file, sep='\t')
metadata = pd.read_csv(metadata_file, sep='\t')

# Merge to add Bacteria_species by matching 'Genome' with 'Accession_2'
analysis_data = analysis_data.merge(
    metadata[['Accession_2', 'organismName']],
    left_on='Genome',
    right_on='Accession_2',
    how='left'
).rename(columns={'organismName': 'Bacteria_species'})

# Merge to add Phage_host_species by matching 'Phage' with 'Prophage_name_matched'
analysis_data = analysis_data.merge(
    metadata[['Prophage_name_matched', 'organismName']],
    left_on='Phage',
    right_on='Prophage_name_matched',
    how='left'
).rename(columns={'organismName': 'Phage_host_species'})

# Drop extra columns generated by the merge
analysis_data = analysis_data.drop(columns=['Accession_2', 'Prophage_name_matched'])

# Check if the species are the same and add a 'Same' column
analysis_data['Same'] = analysis_data.apply(
    lambda row: 'Yes' if row['Bacteria_species'] == row['Phage_host_species'] else 'No',
    axis=1
)

# Save the updated data to a new TSV file
analysis_data.to_csv("06_self_targeting_analysis_with_species.tsv", sep='\t', index=False)

print("Analysis with species matching complete. Results saved to '04_self_targeting_analysis_with_species.tsv'.")

